config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'lp#index'
  get 'top', to: 'top#index'
  get 'images_up_page', to: 'images_up_page#index'
  get 'images_up_page/:app', to: 'images_up_page#index', as: 'app_image_up_page'
  get 'reset_mail', to: 'reset_mail#index'
  get 'registration_mail', to: 'registration_mail#index'
  get 'registration_complete', to: 'registration_complete#index'
  get 'privacy', to: 'privacy#index'

  namespace :img_history do
    get '/', action: :index
  end

  namespace :select_size do
    get '/:id', action: :index, as: 'update'
    get '/', action: :index
  end

  namespace :code_auth do
    post '/', action: :create
    get '/', action: :index
  end

  namespace :inquiry do
    get '/', action: :new
    post '/', action: :create, as: 'send'
  end

  namespace :api do
    namespace :v1 do
      namespace :code_auth do
        post '/', action: :create
        put '/', action: :update
      end
      namespace :img_history do
        get '/', action: :read
        delete '/', action: :delete
      end
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    patch 'users/confirmation', to: 'users/confirmations#confirm', as: 'patch_confirmation'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/top_controller.rb
# frozen_string_literal: true

class TopController < ApplicationController
  def index
    @maintenance_content = SystemNotification.where(display_flag: true)
  end

  private

  def use_before_action?
    false
  end
end

app/views/top/index.html.erb
<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="container">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">

        <% if @maintenance_content.present? %>
          <% @maintenance_content.each do |content| %>
            <div class="row">
              <div class="offset-md-2 col-md-8">
                <div class="card card-warning">
                  <div class="card-header">
                    <div>
                      <span>
                        <i class="fas fa-exclamation-triangle fa-lg"></i>
                      </span>
                      &emsp;
                      <span>お知らせ</span>
                    </div>
                  </div>
                  <div class="card-body">
                    <div class="row">
                      <div class="col-12">
                        <%= simple_format(content[:content]) %>
                      </div>
                    </div>
                    <div class="row">
                      <div class="col-12">
                        <small><%= content[:start_time].strftime('%Y/%m/%d %H:%M') %></small>
                        &nbsp;~&nbsp;
                        <small><%= content[:end_time].strftime('%Y/%m/%d %H:%M') %></small>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>

        <div class="row my-3">
          <div class="offset-md-2 col-md-8">
            <div class="top-logo-frame">
              <%= image_tag('print_logo.png') %>
            </div>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->
    <!-- Main content -->
    <div class="content">
      <div class="container-fluid">
        <div class="row">
          <div class="offset-md-3 col-md-6">
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">写真を撮影して印刷</h5>
                <p class="card-text">
                  <small>名刺の画像を登録して印刷します</small>
                </p>
                <a href="<%= images_up_page_path %>"><button type="button" class="btn btn-block btn-outline-primary btn-lg">名刺を登録</button></a>
              </div>
            </div>
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">登録した名刺から印刷</h5>
                <p class="card-text">
                  <small>過去に登録した名刺を選択して印刷します</small>
                </p>
                <a href="<%= img_history_path %>"><button type="button" class="btn btn-block btn-outline-primary btn-lg">登録名刺一覧へ</button></a>
              </div>
            </div>
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">使い方</h5>
                <p class="card-text">
                  <small>コンビニプリンターの使い方</small>
                </p>
                <a href="https://www.e-printservice.net/shohin/mymeishi" target="_new"><button type="button" class="btn btn-block btn-outline-primary btn-lg">使い方</button></a>
              </div>
            </div>
          </div>
        </div>
        <!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.container -->
</div>
<!-- ./wrapper -->