config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'lp#index'
  get 'top', to: 'top#index'
  get 'images_up_page', to: 'images_up_page#index'
  get 'images_up_page/:app', to: 'images_up_page#index', as: 'app_image_up_page'
  get 'reset_mail', to: 'reset_mail#index'
  get 'registration_mail', to: 'registration_mail#index'
  get 'registration_complete', to: 'registration_complete#index'
  get 'privacy', to: 'privacy#index'

  namespace :img_history do
    get '/', action: :index
  end

  namespace :select_size do
    get '/:id', action: :index, as: 'update'
    get '/', action: :index
  end

  namespace :code_auth do
    post '/', action: :create
    get '/', action: :index
  end

  namespace :inquiry do
    get '/', action: :new
    post '/', action: :create, as: 'send'
  end

  namespace :api do
    namespace :v1 do
      namespace :code_auth do
        post '/', action: :create
        put '/', action: :update
      end
      namespace :img_history do
        get '/', action: :read
        delete '/', action: :delete
      end
    end
  end

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
    passwords: 'users/passwords'
  }
  devise_scope :user do
    patch 'users/confirmation', to: 'users/confirmations#confirm', as: 'patch_confirmation'
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
end

app/controllers/images_up_page_controller.rb
# frozen_string_literal: true

class ImagesUpPageController < ApplicationController
  before_action :authenticate_user!

  def index
    @app_flag = params[:app] == 'app'
  end
end

app/views/images_up_page/index.html.erb
<% content_for :title do %>
名刺選択
<% end %>


<div class="wrapper">
  <!-- Content Wrapper. Contains page content -->
  <div class="container">
    <!-- Content Header (Page header) -->
    <div class="content-header">
      <div class="container-fluid">
        <div class="row mb-2">
          <div class="col-md-6">
            <h1 class="m-0 text-dark">名刺選択</h1>
          </div><!-- /.col -->
          <div class="col-md-6">
            <ol class="breadcrumb float-sm-right">
              <li class="breadcrumb-item"><a href="<%= top_path %>">トップ</a></li>
              <li class="breadcrumb-item active">名刺選択</li>
            </ol>
          </div><!-- /.col -->
        </div><!-- /.row -->
      </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <!-- Main content -->
    <div class="content">
      <div id="container" class="container-fluid">

        <div class="row m-3">
          <% if @app_flag.present? %>
          <div class="offset-md-0 col-md-3 col-6">
            <button type="button" id="startCamera" class="btn btn-primary btn-block py-md-2" onclick="clickStartCamera()">撮影</button>
          </div>
          <div class="offset-md-1 col-md-3 col-6">
            <button type="button" class="btn btn-primary btn-block py-md-2" onclick="$('#myFile').trigger('click')">ファイル選択</button>
          </div>
          <% else %>
          <div class="offset-md-2 col-md-8">
            <div class="row">
              <div class="col-12 text-center h5 p-3 app-link-sentent">
                <span style="display: inline-block;">マイ名刺アプリを利用すれば、</span>
                <span style="display: inline-block;">名刺を撮影するだけで自動認識してトリミング</span>
              </div>
            </div>
            <div class="row app-link-area py-3 py-md-0">
              <div class="offset-md-0 col-md-6 offset-2 col-8 px-4">
                <a href="<%= iOS_link %>">
                  <img class="y-center ios-store" src="<%= image_path('lp/Download_on_the_App_Store_Badge_JP_RGB_blk_100317.svg') %>">
                </a>
              </div>
              <div class="offset-md-0 col-md-6 offset-2 col-8 px-4">
                <a href="<%= android_link %>">
                  <img class="y-center android-store" src="<%= image_path('lp/google-play-badge.png') %>">
                </a>
              </div>
            </div>
            <div class="row mt-5">
              <div class="offset-md-2 col-md-8 offset-2 col-8">
                <button type="button" class="btn btn-primary btn-block py-md-2" onclick="$('#myFile').trigger('click')">ファイルアップロード</button>
              </div>
            </div>
          </div>
          <% end %>
        </div>

        <div id="fileForm" class="row px-3 py-5" style="display: none;">
          <div class="offset-md-1 col-md-6 col-12">
            <div class="input-group">
              <div class="input-group-prepend">
                <span class="input-group-text"><i class="fas fa-image"></i></span>
              </div>
              <input type="text" id="myFileText" class="form-control" readonly="">
              <input id="myFile" type="file" accept="image/*" enctype="multipart/form-data" style="display: none;" />
            </div>
          </div>
        </div>

        <section id="trimmingForm" style="display: none;">
          <div class="row">

            <% if @app_flag.blank? %>
            <div class="col-md-6 mb-4">
              <div class="row align-items-center">
                <div class="col-4">
                  <h5 class="mb-0 pl-3">
                    編集画面
                  </h5>
                </div>
                <div class="col-8">
                  <div class="row">
                    <div class="col-3 text-center pr-1">
                      <button type="button" class="btn btn-success btn-block" onclick="rotateImageCanvasLeft()"><i class="fas fa-undo-alt"></i></button>
                    </div>
                    <div class="col-3 text-center pl-1">
                      <button type="button" class="btn btn-success btn-block" onclick="rotateImageCanvasRight()"><i class="fas fa-redo-alt"></i></button>
                    </div>
                    <div class="col-5 text-center">
                      <button type="button" class="btn btn-danger btn-block" onclick="ResetCanvas()"><small>リセット</small></button>
                    </div>
                  </div>
                </div>
              </div>
              <hr class="mt-1">
              <div id="editImage" class="image-preview">
              </div>
            </div>

            <div class="col-md-6 mb-5">
              <% else %>
              <div class="offset-md-3 col-md-6 mb-5">
                <% end %>
                <h5 class="mb-0 pl-3 preview-title">
                  プレビュー
                </h5>
                <hr class="mt-1">
                <div class="text-center">
                  <div id="baseImage">
                  </div>
                </div>
                <div id="EditBar">
                  <div class="mt-4">
                    明るさ補正
                  </div>
                  <hr class="mt-0">
                  <div class="row align-items-center">
                    <div class="col-2 text-center">
                      0
                    </div>
                    <div class="col-8">
                      <div id="brightnessSlider"></div>
                    </div>
                    <div class="col-2 text-center">
                      100
                    </div>
                  </div>
                  <div class="mt-4">
                    コントラスト補正
                  </div>
                  <hr class="mt-0">
                  <div class="row align-items-center">
                    <div class="col-2 text-center">
                      0
                    </div>
                    <div class="col-8">
                      <div id="contrastSlider"></div>
                    </div>
                    <div class="col-2 text-center">
                      100
                    </div>
                  </div>
                </div>
                <br>
                <button id="confirmTrimming" type="button" class="btn btn-primary btn-block mt-4 mb-5">決定</button>
              </div>
            </div>
            <!-- /.row -->
        </section>
      </div>
      <!-- /.container-fluid -->
    </div>
    <!-- /.content -->
  </div>
  <!-- /.container -->
</div>
<!-- /.wrapper-->
<div id="workCanvas">
  <img id="inputImage" style="display: none;" />
  <canvas id="resizeCanvas" width="1052" height="636" style="display: none;"></canvas>
  <canvas id="rotateCanvas" width="" height="" style="display: none;"></canvas>
</div>

<script>
  let base64Image = null;
  let points = {
    leftTopX: 0,
    leftTopY: 0,
    rightTopX: 0,
    rightTopY: 0,
    rightUnderX: 0,
    rightUnderY: 0,
    leftUnderX: 0,
    leftUnderY: 0
  }
  let brightness = null;
  let contrast = null;
  let canvas;
  let texture;

  let imageWidth = null;
  let imageHeight = null;
  let editWidth = null;
  let editHeight = null;
  let originalCanvas;
  let originalTexture;
  let afterArr = [];
  let base64EditImage = null;
  let imageAngle = 0;

  $(function() {
    resetForm();
    sessionStorage.clear();

    <% if @app_flag.present? %>
      appContrastBar();
      appBrightnessBar();
    <% else %>
      brightnessBar();
      contrastBar();
    <% end %>
    $('#myFile').on('change', function(e) {
      $('#editImage').html('');
      $('#fileForm').show();
      changePreview(e);
    });
    $('#confirmTrimming').on('click', function() {
    <% if @app_flag.present? %>
      appConfirmTrimming();
    <% else %>
      confirmTrimming();
    <% end %>
    });
  });

  function ImgB64Resize() {
    let ImgB64Resize = document.getElementById('resizeCanvas');
    let context = ImgB64Resize.getContext('2d');
    let img = new Image();
    img.onload = function() {
      if (appCheckOS()) {
        context.scale(-1, 1);
        context.translate(-ImgB64Resize.width, 0);
        context.translate(1052, 636); // ずれる分だけ位置を戻す
        context.rotate(180 * Math.PI / 180); // 180度回転
      }
      context.drawImage(img, 0, 0, 1052, 636);
      base64EditImage = document.getElementById('resizeCanvas').toDataURL("image/jpeg");
      sessionStorage.setItem('edit_picture', document.getElementById('resizeCanvas').toDataURL("image/jpeg"));
      window.location.href = '<%= select_size_path %>';
    };
    img.src = base64Image;
  }


  function appCheckOS() {
    if (OS.match(/iPhone|iPad/)){
      if (OS.match(/OS 15_/)) {
      <% if @app_flag.present? %>
        return false;
      <% else %>
        return true;
      <% end %>
      }else{
      <% if @app_flag.present? %>
        return true;
      <% else %>
        return false;
      <% end %>
      }
    }else{
      return false;
    }

  }
</script>